### ISSUE TITLE
cargo test occurs errors!

### ISSUE THREAD

**Issue by qxzhou1010** [mikelodder7/paillier-rs#2]
Hi, I encounter two problem when use this repo.

1. I git clone this repo and use cargo test to run the test case, but the error occurs. Such as:
```
error[E0433]: failed to resolve: use of undeclared crate or module `rand`
   --> tests/paillier.rs:164:39
    |
164 |     let ssk = k256::SecretKey::random(rand::rngs::OsRng::default());
    |                                       ^^^^ use of undeclared crate or module `rand`

error[E0599]: no method named `n` found for enum `Result` in the current scope
   --> tests/paillier.rs:144:20
    |
144 |     assert_eq!(pk1.n(), pk.n());
    |                    ^ method not found in `Result<libpaillier::EncryptionKey, std::string::String>`

Some errors have detailed explanations: E0433, E0599.
For more information about an error, try `rustc --explain E0433`.
```
2. I use this reop an a libary in another project. I use the Encryption and Decryption examples . I execute `cargo run`,  however, the process don't end in long time.

**Comment by mikelodder7** [comment]
1- Fix in [0d8bf9d](https://github.com/mikelodder7/paillier-rs/commit/0d8bf9d3b342304220f1b0fc6ffd5c21ba838c77). Thanks for that.
2- That's most likely the prime generation. You can speed this up by switching to use openssl or gmp feature instead. OpenSSL is often the most efficient with this.

**Comment by qxzhou1010** [comment]
Thank you for your so quickly reply. I update my code and the changes work well. I want to know how to use openssl or gmp feature? what should I do ?

**Comment by mikelodder7** [comment]
In the Cargo.toml file you put

```toml
libpaillier = { version = "0.2", default-features = false, features = ["openssl"] }
```

**Comment by geekbeast** [comment]
@mikelodder7 How long are you expecting key generation to take? On an M1 Max, I have yet to successfully generate keys, after several hours with wasm32-unknown-unknown target. I am now trying with native + gmp and am at north of 15 minutes already.

**Comment by geekbeast** [comment]
Okay, I had forgotten to do --release and now native + gmp -> ~34s which seems reasonable. wasm32-unknown-unknown is very unpredictable. I am seeing anywhere ~120 to up to ~249s.

**Comment by mikelodder7** [comment]
I just relaxed the safe primes requirement so that should help with speeding it up. Let me know what you see.

**Comment by mikelodder7** [comment]
No update in 18 months. Closing.

**Comment by geekbeast** [comment]
@mikelodder7 It is significantly faster now when running wasm32-unknown-unknown. I don't have exact numbers now, but the tests now run faster end to end (39s) than the key generation step was previously taking, but it is on my desktop not my laptop.
