### ISSUE TITLE
Proofs

### ISSUE THREAD

**Issue by donkey-donkey** [mikelodder7/paillier-rs#7]
Hi,
are there any examples of using zero knowledge proofs with the paillier-rs?

**Comment by mikelodder7** [comment]
Is this what you're looking for https://github.com/mikelodder7/paillier-rs/blob/main/src/proof_psf.rs

**Comment by donkey-donkey** [comment]
i dont think so. im thinking more like zk proofs of correct formation of cyphertext and zk proofs of values in range...

**Comment by mikelodder7** [comment]
I don't have it in this code but can add it.

Here's an example of the math for it
- Appendix A in [Lindell'17](https://eprint.iacr.org/2017/552)
- Section 1.2.2 in [Boudot '00](https://www.iacr.org/archive/eurocrypt2000/1807/18070437-new.pdf)

**Comment by donkey-donkey** [comment]
that would be super rad!
also looking for a way to use a zk proof to prove that a plaintext number was encrypted to 2 different public keys.
and of course proving that zero was encrypted.

**Comment by donkey-donkey** [comment]
There are these zk proofs at  https://github.com/ZenGo-X/zk-paillier
They have a non interactive range proof and proof of encrypting zero in there, but they use a different big number solution.

**Comment by s0l0ist** [comment]
I would definitely be interested in the above proofs.

**Comment by donkey-donkey** [comment]
> I would definitely be interested in the above proofs.

do you know how to do them? what is needed?

**Comment by mikelodder7** [comment]
Yes I do. It's just a matter of priorities and time

**Comment by mikelodder7** [comment]
Just added the range proof.
