### ISSUE TITLE
Failure to compile when using `gmp` backend.

### ISSUE THREAD

**Issue by gatoWololo** [mikelodder7/paillier-rs#8]
Hello! Thank you for making this library. We are trying to use `libpaillier` with the GMP backend (as we have measured this backend to be faster than the others). We used to specify this dependency in our `Cargo.toml` as:
```
libpaillier = { version = "0.5", default-features = false, features = ["gmp"] }
```
However this no longer works. We currently get this compilation error:
```rust
error[E0599]: no method named `to_string_radix` found for struct `rug::Integer` in the current scope
  --> /home/user/.cargo/registry/src/index.crates.io-6f17d22bba15001f/unknown_order-0.6.0/src/gmp_backend.rs:46:18
   |
46 |     |b: &Bn| b.0.to_string_radix(16),
   |                  ^^^^^^^^^^^^^^^ method not found in `Integer`
error: could not compile `unknown_order` (lib) due to 4 previous errors
```
Cargo tree (our library is called `tss-ecdsa`):
```
rug v1.24.0
└── unknown_order v0.6.0
    └── libpaillier v0.5.0
        └── tss-ecdsa v0.0.0 (/home/user/Programming/tss-ecdsa)
```
This error happens because `rug` v1.24 changes `to_string_radix` to have a feature cfg on `std`:
```rust
    #[cfg(feature = "std")]
    #[inline]
    pub fn to_string_radix(&self, radix: i32) -> String {
```
I believe `default-features = false` is turning off the `std` feature. So the compiler cannot find this function.

It works if I specify `rug` a separate dependency:
```
libpaillier = { version = "0.5", default-features = false, features = ["gmp"] }
rug = { version = "1.24.0"}
```
But we don't actually directly use `rug`. It took me a while to understand what was happening. Please let me know if there is a better way to specify our `libpaillier` or you consider this a bug on `unknown_order` or `rug`?

Thanks.

**Comment by mikelodder7** [comment]
I believe this has been fixed now in 56e64ebcc04bee17a42323e56dac1dfc65c7f02f
